### PR TITLE
Using Circle CI's fork?

### PR DESCRIPTION
**Pull request by danielcompton**
Circle CI have forked this library and updated it. Would you be interested in deprecating this version and pointing people towards the Circle CI version, or merging this pull request with their changes?

### CODE REVIEW

**Comment by technomancy** [comment]
I'd be happy to add a collaborator to this repo who is interested in continuing to maintain it. I haven't used it for many years and am not in a position to continue maintenance.

**Comment by technomancy** [comment]
I could deprecrate this repo and point people to the other one too if people prefer; I just would be slightly more inclined to keep things at this repo to minimize confusion.

**Comment by danielcompton** [comment]
I'm happy to step up as a collaborator, we're using it at work.

**Comment by technomancy** [comment]
Sure thing; you got it. Is your Clojars username the same as your GitHub username?

**Comment by danielcompton** [comment]
Yep: https://clojars.org/danielcompton

**Comment by technomancy** [comment]
Thanks; I've added you to clojars.

**Comment by danielcompton** [comment]
Thankyou :)

**Pull request merged**
